image: tetraweb/php

stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - echo "Building plugin..."
    - npm install
    - composer run build-production

deploy-job:
  stage: deploy
  environment: production
  artifacts:
    paths:
      - kudos-donations.zip
  script:
    - echo "Deploying application..."
    - composer run make-zip
    - echo "Application successfully built."
