version: "3.3"

services:
  wordpress:
    image: "wordpress:${WP_VERSION:-5.5}-php${PHP_VERSION:-7.2}"
    volumes:
      - wp:/var/www/html
      - ../:/var/www/html/wp-content/plugins/kudos-donations:ro
      - ../../kudos-premium:/var/www/html/wp-content/plugins/kudos-premium:ro
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
  #      WORDPRESS_DEBUG: "${WORDPRESS_DEBUG:-false}"

  wp-cli:
    image: "wordpress:cli-${WP_CLI_VERSION:-2.2.0}-php${PHP_VERSION:-7.3}"
    #    environment:
    #      - APACHE_RUN_USER="www-data"
    #      - APACHE_RUN_GROUP="www-data"
    depends_on:
      - "db"
    volumes:
      - "wp:/var/www/html:rw"
      - "./bin/install-wp.sh:/usr/local/bin/install-wp:ro"
      - ../:/var/www/html/wp-content/plugins/kudos-donations:ro

  db:
    image: mariadb:10.5
    volumes:
      - db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  adminer:
    image: adminer
    container_name: adminer-kudos
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  wp: { }
  db: { }