version: "3.3"

services:
  wordpress:
    build:
      context: .
      args:
        PHP_VERSION: 7.2
        WORDPRESS_VERSION: 5.4
    container_name: wordpress-kudos
    volumes:
      - ${WORDPRESS_DIR:-./wordpress}:/var/www/html
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ../:/var/www/html/wp-content/plugins/kudos-donations:ro
    ports:
      - "80:80"
    restart: always
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_SITEURL', 'http://' . $$_SERVER['HTTP_HOST']);
        define('WP_HOME', 'http://' . $$_SERVER['HTTP_HOST']);
        define('WP_DEBUG_LOG', true);
        define('FS_METHOD','direct');
        define('SCRIPT_DEBUG', true);
        $$redis_server = array(
            'host'     => 'redis',
            'port'     => 6379,
            'auth'     => ${REDIS_PASSWORD:-123},
            'database' => 0, // Optionally use a specific numeric Redis database. Default is 0.
        );

  db:
    image: mariadb:10.5
    container_name: db-kudos
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  adminer:
    image: adminer
    container_name: adminer-kudos
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

  redis:
    image: redis:alpine
    container_name: redis-kudos
    restart: always
    networks:
      - default
    command: redis-server --requirepass ${REDIS_PASSWORD:-123}

volumes:
  db_data:

