version: "3.3"

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress-kudos
    volumes:
      - ./wordpress:/var/www/html
      - ../:/var/www/html/wp-content/plugins/kudos-donations
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_SITEURL', 'http://' . $$_SERVER['HTTP_HOST']);
        define('WP_HOME', 'http://' . $$_SERVER['HTTP_HOST']);
        define('WP_DEBUG_LOG', true);

  db:
    image: mariadb:10.5
    container_name: db-kudos
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  ngrok:
    image: wernight/ngrok
    container_name: ngrok-kudos
    ports:
      - "4040:4040"
    environment:
      NGROK_PORT: wordpress:80
      NGROK_REGION: eu

volumes:
  db_data:
  wordpress:

