services:
  # Default configuration for services
  _defaults:
    autowire: true
    public: true

  # Base plugin services
  IseardMedia\Kudos\:
    resource: '../includes/*'
    exclude: '../includes/{namespace.php,functions.php,helpers.php,index.php}'

  # Logger setup
  Monolog\Handler\RotatingFileHandler:
    arguments:
      - '%env(KUDOS_STORAGE_DIR)%logs/%env(APP_ENV)%.log'
      - '5'
      - '%env(LOG_LEVEL)%'

  Monolog\Handler\WhatFailureGroupHandler:
    arguments:
      - [ '@Monolog\Handler\RotatingFileHandler' ]

  Psr\Log\LoggerInterface:
    class: Monolog\Logger
    arguments: [ 'kudos_donations' ]
    calls:
      - method: pushHandler
        arguments: [ '@Monolog\Handler\WhatFailureGroupHandler' ]

  # External libraries
  Dompdf\Dompdf: ~
  Mollie\Api\MollieApiClient: ~

  _instanceof:

    # Add logger to relevant services
    Psr\Log\LoggerAwareInterface:
      calls:
        - method: setLogger
          arguments: [ '@Psr\Log\LoggerInterface' ]

    # Service tagging
    IseardMedia\Kudos\Container\Registrable:
      tags: ['kudos.registrable']
    IseardMedia\Kudos\Container\ActivationAwareInterface:
      tags: ['kudos.activation']
    IseardMedia\Kudos\Container\UpgradeAwareInterface:
      tags: ['kudos.upgradeable']
    IseardMedia\Kudos\Container\HasSettingsInterface:
      tags: ['kudos.has_settings']
    IseardMedia\Kudos\Migrations\MigrationInterface:
      tags: ['kudos.migration']
    IseardMedia\Kudos\Vendor\PaymentVendor\PaymentVendorInterface:
      tags: ['kudos.payment_vendor']
    IseardMedia\Kudos\Vendor\EmailVendor\EmailVendorInterface:
      tags: ['kudos.email_vendor']
    IseardMedia\Kudos\Container\EncryptionAwareInterface:
      calls:
        - method: set_encryption
          arguments: [ '@IseardMedia\Kudos\Service\EncryptionService' ]

  # PaymentVendorFactory
  IseardMedia\Kudos\Vendor\PaymentVendor\PaymentVendorFactory:
    arguments:
      - !tagged_iterator 'kudos.payment_vendor'

  # EmailVendorFactory
  IseardMedia\Kudos\Vendor\EmailVendor\EmailVendorFactory:
    arguments:
      - !tagged_iterator 'kudos.email_vendor'

  # RegistrableHandler
  IseardMedia\Kudos\Container\Handler\RegistrableHandler:
    arguments:
      - !tagged_iterator 'kudos.registrable'

  # SettingsHandler
  IseardMedia\Kudos\Container\Handler\SettingsHandler:
    arguments:
      - !tagged_iterator 'kudos.has_settings'

  # ActivationHandler
  IseardMedia\Kudos\Container\Handler\ActivationHandler:
    arguments:
      - !tagged_iterator 'kudos.activation'

  # UpgradeHandler
  IseardMedia\Kudos\Container\Handler\UpgradeHandler:
    arguments:
      - !tagged_iterator 'kudos.upgradeable'

# Filter to allow external modification (optional)
  kudos_container_configurator:
    class: IseardMedia\Kudos\Service\ContainerConfigurator
    arguments:
      - '@service_container'
    calls:
      - method: apply_filters
        arguments:
          - 'kudos_container_configurator'
          - '@service_container'