<?php
/**
 * Utils.
 *
 * @link https://github.com/mikey242/kudos-donations/
 *
 * @copyright 2025 Iseard Media
 */

declare(strict_types=1);

namespace IseardMedia\Kudos\Helper;

class Country {

	/**
	 * List of country codes and translated names.
	 */
	public static function get_countries(): array {
		return [
			'AF' => __( 'Afghanistan', 'kudos-donations' ),
			'AX' => __( 'Åland Islands', 'kudos-donations' ),
			'AL' => __( 'Albania', 'kudos-donations' ),
			'DZ' => __( 'Algeria', 'kudos-donations' ),
			'AS' => __( 'American Samoa', 'kudos-donations' ),
			'AD' => __( 'Andorra', 'kudos-donations' ),
			'AO' => __( 'Angola', 'kudos-donations' ),
			'AI' => __( 'Anguilla', 'kudos-donations' ),
			'AQ' => __( 'Antarctica', 'kudos-donations' ),
			'AG' => __( 'Antigua and Barbuda', 'kudos-donations' ),
			'AR' => __( 'Argentina', 'kudos-donations' ),
			'AM' => __( 'Armenia', 'kudos-donations' ),
			'AW' => __( 'Aruba', 'kudos-donations' ),
			'AU' => __( 'Australia', 'kudos-donations' ),
			'AT' => __( 'Austria', 'kudos-donations' ),
			'AZ' => __( 'Azerbaijan', 'kudos-donations' ),
			'BS' => __( 'Bahamas', 'kudos-donations' ),
			'BH' => __( 'Bahrain', 'kudos-donations' ),
			'BD' => __( 'Bangladesh', 'kudos-donations' ),
			'BB' => __( 'Barbados', 'kudos-donations' ),
			'BY' => __( 'Belarus', 'kudos-donations' ),
			'BE' => __( 'Belgium', 'kudos-donations' ),
			'BZ' => __( 'Belize', 'kudos-donations' ),
			'BJ' => __( 'Benin', 'kudos-donations' ),
			'BM' => __( 'Bermuda', 'kudos-donations' ),
			'BT' => __( 'Bhutan', 'kudos-donations' ),
			'BO' => __( 'Bolivia', 'kudos-donations' ),
			'BA' => __( 'Bosnia and Herzegovina', 'kudos-donations' ),
			'BW' => __( 'Botswana', 'kudos-donations' ),
			'BV' => __( 'Bouvet Island', 'kudos-donations' ),
			'BR' => __( 'Brazil', 'kudos-donations' ),
			'IO' => __( 'British Indian Ocean Territory', 'kudos-donations' ),
			'BN' => __( 'Brunei Darussalam', 'kudos-donations' ),
			'BG' => __( 'Bulgaria', 'kudos-donations' ),
			'BF' => __( 'Burkina Faso', 'kudos-donations' ),
			'BI' => __( 'Burundi', 'kudos-donations' ),
			'KH' => __( 'Cambodia', 'kudos-donations' ),
			'CM' => __( 'Cameroon', 'kudos-donations' ),
			'CA' => __( 'Canada', 'kudos-donations' ),
			'CV' => __( 'Cape Verde', 'kudos-donations' ),
			'KY' => __( 'Cayman Islands', 'kudos-donations' ),
			'CF' => __( 'Central African Republic', 'kudos-donations' ),
			'TD' => __( 'Chad', 'kudos-donations' ),
			'CL' => __( 'Chile', 'kudos-donations' ),
			'CN' => __( 'China', 'kudos-donations' ),
			'CX' => __( 'Christmas Island', 'kudos-donations' ),
			'CC' => __( 'Cocos (Keeling) Islands', 'kudos-donations' ),
			'CO' => __( 'Colombia', 'kudos-donations' ),
			'KM' => __( 'Comoros', 'kudos-donations' ),
			'CG' => __( 'Congo', 'kudos-donations' ),
			'CD' => __( 'Congo, The Democratic Republic of The', 'kudos-donations' ),
			'CK' => __( 'Cook Islands', 'kudos-donations' ),
			'CR' => __( 'Costa Rica', 'kudos-donations' ),
			'CI' => __( "Cote D'ivoire", 'kudos-donations' ),
			'HR' => __( 'Croatia', 'kudos-donations' ),
			'CU' => __( 'Cuba', 'kudos-donations' ),
			'CY' => __( 'Cyprus', 'kudos-donations' ),
			'CZ' => __( 'Czechia', 'kudos-donations' ),
			'DK' => __( 'Denmark', 'kudos-donations' ),
			'DJ' => __( 'Djibouti', 'kudos-donations' ),
			'DM' => __( 'Dominica', 'kudos-donations' ),
			'DO' => __( 'Dominican Republic', 'kudos-donations' ),
			'EC' => __( 'Ecuador', 'kudos-donations' ),
			'EG' => __( 'Egypt', 'kudos-donations' ),
			'SV' => __( 'El Salvador', 'kudos-donations' ),
			'GQ' => __( 'Equatorial Guinea', 'kudos-donations' ),
			'ER' => __( 'Eritrea', 'kudos-donations' ),
			'EE' => __( 'Estonia', 'kudos-donations' ),
			'ET' => __( 'Ethiopia', 'kudos-donations' ),
			'FK' => __( 'Falkland Islands (Malvinas', 'kudos-donations' ),
			'FO' => __( 'Faroe Islands', 'kudos-donations' ),
			'FJ' => __( 'Fiji', 'kudos-donations' ),
			'FI' => __( 'Finland', 'kudos-donations' ),
			'FR' => __( 'France', 'kudos-donations' ),
			'GF' => __( 'French Guiana', 'kudos-donations' ),
			'PF' => __( 'French Polynesia', 'kudos-donations' ),
			'TF' => __( 'French Southern Territories', 'kudos-donations' ),
			'GA' => __( 'Gabon', 'kudos-donations' ),
			'GM' => __( 'Gambia', 'kudos-donations' ),
			'GE' => __( 'Georgia', 'kudos-donations' ),
			'DE' => __( 'Germany', 'kudos-donations' ),
			'GH' => __( 'Ghana', 'kudos-donations' ),
			'GI' => __( 'Gibraltar', 'kudos-donations' ),
			'GR' => __( 'Greece', 'kudos-donations' ),
			'GL' => __( 'Greenland', 'kudos-donations' ),
			'GD' => __( 'Grenada', 'kudos-donations' ),
			'GP' => __( 'Guadeloupe', 'kudos-donations' ),
			'GU' => __( 'Guam', 'kudos-donations' ),
			'GT' => __( 'Guatemala', 'kudos-donations' ),
			'GG' => __( 'Guernsey', 'kudos-donations' ),
			'GN' => __( 'Guinea', 'kudos-donations' ),
			'GW' => __( 'Guinea-bissau', 'kudos-donations' ),
			'GY' => __( 'Guyana', 'kudos-donations' ),
			'HT' => __( 'Haiti', 'kudos-donations' ),
			'HM' => __( 'Heard Island and Mcdonald Islands', 'kudos-donations' ),
			'VA' => __( 'Holy See (Vatican City State', 'kudos-donations' ),
			'HN' => __( 'Honduras', 'kudos-donations' ),
			'HK' => __( 'Hong Kong', 'kudos-donations' ),
			'HU' => __( 'Hungary', 'kudos-donations' ),
			'IS' => __( 'Iceland', 'kudos-donations' ),
			'IN' => __( 'India', 'kudos-donations' ),
			'ID' => __( 'Indonesia', 'kudos-donations' ),
			'IR' => __( 'Iran, Islamic Republic of', 'kudos-donations' ),
			'IQ' => __( 'Iraq', 'kudos-donations' ),
			'IE' => __( 'Ireland', 'kudos-donations' ),
			'IM' => __( 'Isle of Man', 'kudos-donations' ),
			'IL' => __( 'Israel', 'kudos-donations' ),
			'IT' => __( 'Italy', 'kudos-donations' ),
			'JM' => __( 'Jamaica', 'kudos-donations' ),
			'JP' => __( 'Japan', 'kudos-donations' ),
			'JE' => __( 'Jersey', 'kudos-donations' ),
			'JO' => __( 'Jordan', 'kudos-donations' ),
			'KZ' => __( 'Kazakhstan', 'kudos-donations' ),
			'KE' => __( 'Kenya', 'kudos-donations' ),
			'KI' => __( 'Kiribati', 'kudos-donations' ),
			'KP' => __( "Korea, Democratic People's Republic of", 'kudos-donations' ),
			'KR' => __( 'Korea, Republic of', 'kudos-donations' ),
			'KW' => __( 'Kuwait', 'kudos-donations' ),
			'KG' => __( 'Kyrgyzstan', 'kudos-donations' ),
			'LA' => __( "Lao People's Democratic Republic", 'kudos-donations' ),
			'LV' => __( 'Latvia', 'kudos-donations' ),
			'LB' => __( 'Lebanon', 'kudos-donations' ),
			'LS' => __( 'Lesotho', 'kudos-donations' ),
			'LR' => __( 'Liberia', 'kudos-donations' ),
			'LY' => __( 'Libyan Arab Jamahiriya', 'kudos-donations' ),
			'LI' => __( 'Liechtenstein', 'kudos-donations' ),
			'LT' => __( 'Lithuania', 'kudos-donations' ),
			'LU' => __( 'Luxembourg', 'kudos-donations' ),
			'MO' => __( 'Macao', 'kudos-donations' ),
			'MK' => __( 'Macedonia, The Former Yugoslav Republic of', 'kudos-donations' ),
			'MG' => __( 'Madagascar', 'kudos-donations' ),
			'MW' => __( 'Malawi', 'kudos-donations' ),
			'MY' => __( 'Malaysia', 'kudos-donations' ),
			'MV' => __( 'Maldives', 'kudos-donations' ),
			'ML' => __( 'Mali', 'kudos-donations' ),
			'MT' => __( 'Malta', 'kudos-donations' ),
			'MH' => __( 'Marshall Islands', 'kudos-donations' ),
			'MQ' => __( 'Martinique', 'kudos-donations' ),
			'MR' => __( 'Mauritania', 'kudos-donations' ),
			'MU' => __( 'Mauritius', 'kudos-donations' ),
			'YT' => __( 'Mayotte', 'kudos-donations' ),
			'MX' => __( 'Mexico', 'kudos-donations' ),
			'FM' => __( 'Micronesia, Federated States of', 'kudos-donations' ),
			'MD' => __( 'Moldova, Republic of', 'kudos-donations' ),
			'MC' => __( 'Monaco', 'kudos-donations' ),
			'MN' => __( 'Mongolia', 'kudos-donations' ),
			'ME' => __( 'Montenegro', 'kudos-donations' ),
			'MS' => __( 'Montserrat', 'kudos-donations' ),
			'MA' => __( 'Morocco', 'kudos-donations' ),
			'MZ' => __( 'Mozambique', 'kudos-donations' ),
			'MM' => __( 'Myanmar', 'kudos-donations' ),
			'NA' => __( 'Namibia', 'kudos-donations' ),
			'NR' => __( 'Nauru', 'kudos-donations' ),
			'NP' => __( 'Nepal', 'kudos-donations' ),
			'NL' => __( 'Netherlands', 'kudos-donations' ),
			'AN' => __( 'Netherlands Antilles', 'kudos-donations' ),
			'NC' => __( 'New Caledonia', 'kudos-donations' ),
			'NZ' => __( 'New Zealand', 'kudos-donations' ),
			'NI' => __( 'Nicaragua', 'kudos-donations' ),
			'NE' => __( 'Niger', 'kudos-donations' ),
			'NG' => __( 'Nigeria', 'kudos-donations' ),
			'NU' => __( 'Niue', 'kudos-donations' ),
			'NF' => __( 'Norfolk Island', 'kudos-donations' ),
			'MP' => __( 'Northern Mariana Islands', 'kudos-donations' ),
			'NO' => __( 'Norway', 'kudos-donations' ),
			'OM' => __( 'Oman', 'kudos-donations' ),
			'PK' => __( 'Pakistan', 'kudos-donations' ),
			'PW' => __( 'Palau', 'kudos-donations' ),
			'PS' => __( 'Palestinian Territory, Occupied', 'kudos-donations' ),
			'PA' => __( 'Panama', 'kudos-donations' ),
			'PG' => __( 'Papua New Guinea', 'kudos-donations' ),
			'PY' => __( 'Paraguay', 'kudos-donations' ),
			'PE' => __( 'Peru', 'kudos-donations' ),
			'PH' => __( 'Philippines', 'kudos-donations' ),
			'PN' => __( 'Pitcairn', 'kudos-donations' ),
			'PL' => __( 'Poland', 'kudos-donations' ),
			'PT' => __( 'Portugal', 'kudos-donations' ),
			'PR' => __( 'Puerto Rico', 'kudos-donations' ),
			'QA' => __( 'Qatar', 'kudos-donations' ),
			'RE' => __( 'Reunion', 'kudos-donations' ),
			'RO' => __( 'Romania', 'kudos-donations' ),
			'RU' => __( 'Russian Federation', 'kudos-donations' ),
			'RW' => __( 'Rwanda', 'kudos-donations' ),
			'SH' => __( 'Saint Helena', 'kudos-donations' ),
			'KN' => __( 'Saint Kitts and Nevis', 'kudos-donations' ),
			'LC' => __( 'Saint Lucia', 'kudos-donations' ),
			'PM' => __( 'Saint Pierre and Miquelon', 'kudos-donations' ),
			'VC' => __( 'Saint Vincent and The Grenadines', 'kudos-donations' ),
			'WS' => __( 'Samoa', 'kudos-donations' ),
			'SM' => __( 'San Marino', 'kudos-donations' ),
			'ST' => __( 'Sao Tome and Principe', 'kudos-donations' ),
			'SA' => __( 'Saudi Arabia', 'kudos-donations' ),
			'SN' => __( 'Senegal', 'kudos-donations' ),
			'RS' => __( 'Serbia', 'kudos-donations' ),
			'SC' => __( 'Seychelles', 'kudos-donations' ),
			'SL' => __( 'Sierra Leone', 'kudos-donations' ),
			'SG' => __( 'Singapore', 'kudos-donations' ),
			'SK' => __( 'Slovakia', 'kudos-donations' ),
			'SI' => __( 'Slovenia', 'kudos-donations' ),
			'SB' => __( 'Solomon Islands', 'kudos-donations' ),
			'SO' => __( 'Somalia', 'kudos-donations' ),
			'ZA' => __( 'South Africa', 'kudos-donations' ),
			'GS' => __( 'South Georgia and The South Sandwich Islands', 'kudos-donations' ),
			'ES' => __( 'Spain', 'kudos-donations' ),
			'LK' => __( 'Sri Lanka', 'kudos-donations' ),
			'SD' => __( 'Sudan', 'kudos-donations' ),
			'SR' => __( 'Suriname', 'kudos-donations' ),
			'SJ' => __( 'Svalbard and Jan Mayen', 'kudos-donations' ),
			'SZ' => __( 'Swaziland', 'kudos-donations' ),
			'SE' => __( 'Sweden', 'kudos-donations' ),
			'CH' => __( 'Switzerland', 'kudos-donations' ),
			'SY' => __( 'Syrian Arab Republic', 'kudos-donations' ),
			'TW' => __( 'Taiwan, Province of China', 'kudos-donations' ),
			'TJ' => __( 'Tajikistan', 'kudos-donations' ),
			'TZ' => __( 'Tanzania, United Republic of', 'kudos-donations' ),
			'TH' => __( 'Thailand', 'kudos-donations' ),
			'TL' => __( 'Timor-leste', 'kudos-donations' ),
			'TG' => __( 'Togo', 'kudos-donations' ),
			'TK' => __( 'Tokelau', 'kudos-donations' ),
			'TO' => __( 'Tonga', 'kudos-donations' ),
			'TT' => __( 'Trinidad and Tobago', 'kudos-donations' ),
			'TN' => __( 'Tunisia', 'kudos-donations' ),
			'TR' => __( 'Turkey', 'kudos-donations' ),
			'TM' => __( 'Turkmenistan', 'kudos-donations' ),
			'TC' => __( 'Turks and Caicos Islands', 'kudos-donations' ),
			'TV' => __( 'Tuvalu', 'kudos-donations' ),
			'UG' => __( 'Uganda', 'kudos-donations' ),
			'UA' => __( 'Ukraine', 'kudos-donations' ),
			'AE' => __( 'United Arab Emirates', 'kudos-donations' ),
			'GB' => __( 'United Kingdom', 'kudos-donations' ),
			'US' => __( 'United States', 'kudos-donations' ),
			'UM' => __( 'United States Minor Outlying Islands', 'kudos-donations' ),
			'UY' => __( 'Uruguay', 'kudos-donations' ),
			'UZ' => __( 'Uzbekistan', 'kudos-donations' ),
			'VU' => __( 'Vanuatu', 'kudos-donations' ),
			'VE' => __( 'Venezuela', 'kudos-donations' ),
			'VN' => __( 'Viet Nam', 'kudos-donations' ),
			'VG' => __( 'Virgin Islands, British', 'kudos-donations' ),
			'VI' => __( 'Virgin Islands, U.S', 'kudos-donations' ),
			'WF' => __( 'Wallis and Futuna', 'kudos-donations' ),
			'EH' => __( 'Western Sahara', 'kudos-donations' ),
			'YE' => __( 'Yemen', 'kudos-donations' ),
			'ZM' => __( 'Zambia', 'kudos-donations' ),
			'ZW' => __( 'Zimbabwe', 'kudos-donations' ),
		];
	}

	/**
	 * Get the ISO code by country name.
	 *
	 * @param string $country_name The full name of the country.
	 * @return string|null The two-letter ISO code or null if not found.
	 */
	public static function get_iso_code_by_name( string $country_name ): ?string {
		// Use array_flip to quickly search by value (country name) and return the key (code).
		$flipped = array_flip( self::get_countries() );
		// Use case-insensitive comparison.
		foreach ( $flipped as $name => $code ) {
			if ( strcasecmp( $country_name, $name ) === 0 ) {
				return $code;
			}
		}
		return null; // Return null if the country name is not found.
	}
}
