name: Release Workflow

on:
    push:
        tags: ['*']

jobs:
    release:
        permissions:
            contents: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Set up PHP with Composer and PHP-Scoper
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.2
                  tools: composer, php-scoper
                  coverage: none

            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                cache: "npm"
                node-version-file: '.nvmrc'

            - name: Get composer cache directory
              id: composer-cache
              run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - name: Cache dependencies
              uses: actions/cache@v5
              with:
                path: ${{ steps.composer-cache.outputs.dir }}
                key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                restore-keys: ${{ runner.os }}-composer-

            - name: Install dependencies
              run: |
                npm ci
                composer install --no-ansi --no-interaction --no-progress --prefer-dist --no-dev --optimize-autoloader

            - name: Build front-end assets
              run: npm run build

            - name: Create zip archive
              run: |
                  curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
                  chmod +x wp-cli.phar
                  php wp-cli.phar package install wp-cli/dist-archive-command:3.1.0 --allow-root
                  composer run make-zip

            - name: Upload artifact
              uses: actions/upload-artifact@v7
              with:
                  name: release
                  path: kudos-donations.zip

            - name: Publish GitHub Release
              uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe
              with:
                  body: |
                      ## What's Changed
                      - Automatically generated release.
                  files: kudos-donations.zip
